stages:
  - build
  - package

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo

build:
  image: 'rust:latest'
  stage: build
  tags:
    - rust
  before_script:
    - rustc --version && cargo --version
    - cargo test
  script:
    - cargo build --release
  after_script:
    - test -e /artifacts || mkdir /artifacts
    - find target/release -maxdepth 1 -executable -type f -exec cp -r "{}" /artifacts/ \;
  artifacts:
    paths:
      - /artifacts/
    expire_in: 1 week
  cache:
    paths:
      - $CARGO_HOME

